// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcE1z9KAgpwFaix7pNDHENqFKycq8hwF4',
    appId: '1:662027997687:web:bd9c0a0901406dfb99def2',
    messagingSenderId: '662027997687',
    projectId: 'naim-7bca7',
    authDomain: 'naim-7bca7.firebaseapp.com',
    storageBucket: 'naim-7bca7.firebasestorage.app',
    measurementId: 'G-N3SH46VQS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx9-BetOAh_VVeH9OB4ekERyT_loq5me8',
    appId: '1:662027997687:android:e678abc15e9cec2a99def2',
    messagingSenderId: '662027997687',
    projectId: 'naim-7bca7',
    storageBucket: 'naim-7bca7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNnVN9Zy2i-li4NasGwSa5dcwM3zMtTes',
    appId: '1:662027997687:ios:f830bbc9b8a2529c99def2',
    messagingSenderId: '662027997687',
    projectId: 'naim-7bca7',
    storageBucket: 'naim-7bca7.firebasestorage.app',
    iosClientId: '662027997687-8r33oe07b2r4ejlkmfrii344cet1fqqo.apps.googleusercontent.com',
    iosBundleId: 'an.naim.library',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNnVN9Zy2i-li4NasGwSa5dcwM3zMtTes',
    appId: '1:662027997687:ios:f830bbc9b8a2529c99def2',
    messagingSenderId: '662027997687',
    projectId: 'naim-7bca7',
    storageBucket: 'naim-7bca7.firebasestorage.app',
    iosClientId: '662027997687-8r33oe07b2r4ejlkmfrii344cet1fqqo.apps.googleusercontent.com',
    iosBundleId: 'an.naim.library',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcE1z9KAgpwFaix7pNDHENqFKycq8hwF4',
    appId: '1:662027997687:web:5fa6b869ecf366dd99def2',
    messagingSenderId: '662027997687',
    projectId: 'naim-7bca7',
    authDomain: 'naim-7bca7.firebaseapp.com',
    storageBucket: 'naim-7bca7.firebasestorage.app',
    measurementId: 'G-TCZRYM58P8',
  );
}
